apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-external
  labels:
    type: local
spec:
  storageClassName: calibre-external
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "$CALIBREEXTERNALDIR/external"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-external
spec:
  storageClassName: calibre-external
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-config
  labels:
    type: local
spec:
  storageClassName: calibre-config
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "$VOLUMESDIR/out/vol-calibre-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
spec:
  storageClassName: calibre-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-data
  labels:
    type: local
spec:
  storageClassName: calibre-data
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "$VOLUMESDIR/out/vol-calibre-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-data
spec:
  storageClassName: calibre-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre
spec:
  selector:
    matchLabels:
      app: calibre
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
      - image: lscr.io/linuxserver/calibre:latest
        securityContext:
          # runAsUser: 50001
          # runAsGroup: 40000
          # fsGroup: 40000
          seccompProfile:
            type: Unconfined
        env:
          - name: PUID
            value: "50001"
          - name: PGID
            value: "40000"
          - name: TZ
            value: "America/Fortaleza"
          - name: PASSWORD
            value: "l31tur@"
          # - name: CLI_ARGS
          #   value: ..
        name: calibre
        ports:
        - containerPort: 8080
          name: cdg
        - containerPort: 8181
          name: cdgh
        - containerPort: 8081
          name: cwg
        volumeMounts:
        - name: calibre-config
          mountPath: /config
        - name: calibre-data
          mountPath: /data
        - name: calibre-c
          mountPath: /c
        stdin: true
        tty: true
        resources:
          limits:
            # cpu: 1
            memory: 1024Mi
          requests: 
            # cpu: 1
            memory: 1024Mi
      volumes:
        - name: calibre-c
          persistentVolumeClaim:
            claimName: calibre-external
        - name: calibre-config
          persistentVolumeClaim:
            claimName: calibre-config
        - name: calibre-data
          persistentVolumeClaim:
            claimName: calibre-data
---
apiVersion: v1
kind: Service
metadata:
  name: calibre
spec:
  type: NodePort
  selector:
    app: calibre
  ports:
    - name: "30180"
      protocol: TCP
      port: 30180
      targetPort: 8080
      nodePort: 30180
    - name: "30181"
      protocol: TCP
      port: 30181
      targetPort: 8181
      nodePort: 30181
    - name: "30182"
      protocol: TCP
      port: 30182
      targetPort: 8081
      nodePort: 30182
