apiVersion: v1
kind: PersistentVolume
metadata:
  name: dorbletapache
  labels:
    type: local
spec:
  storageClassName: dorbletapache
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/development/egt/customers/egt/dorb/dorblet"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dorbletapache
spec:
  storageClassName: dorbletapache
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorbletapache
spec:
  selector:
    matchLabels:
      app: dorbletapache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dorbletapache
    spec:
      containers:
      - image: pedrofmj/php-apache-egt:7.4
        name: dorbletapache
        ports:
        - containerPort: 80
          name: dorbletapache
        volumeMounts:
        - name: dorbletapache
          mountPath: /var/www/html
        stdin: true
        tty: true
      volumes:
        - name: dorbletapache
          persistentVolumeClaim:
            claimName: dorbletapache
---
apiVersion: v1
kind: Service
metadata:
  name: dorbletapache
spec:
  type: NodePort
  selector:
    app: dorbletapache
  ports:
    - name: "80"
      protocol: TCP
      port: 50000
      targetPort: 80
