apiVersion: v1
kind: PersistentVolume
metadata:
  name: onedev
  labels:
    type: local
spec:
  storageClassName: onedev
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "$VOLUMESDIR/out/vol-onedev"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onedev
spec:
  storageClassName: onedev
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: onedev
spec:
  selector:
    matchLabels:
      app: onedev
  template:
    metadata:
      labels:
        app: onedev
    spec:
      containers:
      - image: 1dev/server
        name: onedev
        ports:
        - containerPort: 6610
          name: onedev-0
        - containerPort: 6611
          name: onedev-1
        volumeMounts:
        - name: onedev
          mountPath: /opt/onedev
        stdin: true
        tty: true
      volumes:
        - name: onedev
          persistentVolumeClaim:
            claimName: onedev
---
apiVersion: v1
kind: Service
metadata:
  name: onedev
spec:
  type: NodePort
  selector:
    app: onedev
  ports:
    - name: "30610"
      protocol: TCP
      port: 30610
      targetPort: 6610
      nodePort: 30610
    - name: "30611"
      protocol: TCP
      port: 30611
      targetPort: 6611
      nodePort: 30611
