apiVersion: v1
kind: PersistentVolume
metadata:
  name: pingdirectory-opt-out
  labels:
    type: local
spec:
  storageClassName: pingdirectory-opt-out
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/development/devops/volumes/pingdirectory-opt-out"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingdirectory-opt-out
spec:
  storageClassName: pingdirectory-opt-out
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdirectory
spec:
  selector:
    matchLabels:
      app: pingdirectory
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pingdirectory
    spec:
      securityContext:
        fsGroup: 0
        runAsUser: 9031
        runAsGroup: 0
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: pingidentity/pingdirectory
        name: pingdirectory
        ports:
        - containerPort: 1389
          name: ldap
        - containerPort: 1636
          name: ldaps
        - containerPort: 1443
          name: web
        volumeMounts:
        - name: pingdirectory-config
          mountPath: /opt/staging/pd.profile/server-root/pre-setup/PingDirectory.lic
          subPath: PingDirectory.lic
        - name: pingdirectory-opt-out
          mountPath: /opt/out
        stdin: true
        tty: true
      volumes:
      - name: pingdirectory-config
        configMap:
          name: pingdirectory-config
      - name: pingdirectory-opt-out
        persistentVolumeClaim:
          claimName: pingdirectory-opt-out
---
apiVersion: v1
kind: Service
metadata:
  name: pingdirectory
spec:
  type: NodePort
  selector:
    app: pingdirectory
  ports:
    - name: "1389"
      protocol: TCP
      port: 1389
      targetPort: 1389
    - name: "1636"
      protocol: TCP
      port: 1636
      targetPort: 1636
    - name: "1443"
      protocol: TCP
      port: 1443
      targetPort: 1443
